import { Category, Term } from './types';

export const TERMS_DATA: Term[] = [
  {
    id: 'prd',
    word: 'PRD (기획서)',
    category: Category.PLANNING,
    definition: 'Product Requirements Document의 약자로, 제품이 갖춰야 할 기능과 요구사항을 상세하게 적은 문서입니다.',
    simpleExplanation: '집을 지을 때 필요한 "건축 설계도"와 같아요. AI에게 코딩을 시키기 전에 "나는 이런 앱을 원해"라고 아주 자세하게 설명하는 글입니다.',
    analogy: '인테리어 업자에게 "그냥 예쁘게 해주세요"라고 하면 망하죠? "벽지는 흰색, 바닥은 나무 무늬, 조명은 노란색으로 해주세요"라고 적어주는 주문서입니다.',
    examplePrompt: '내가 만들고 싶은 앱은 "반려동물 식단 관리 앱"이야. 주요 기능은 식단 기록, 칼로리 계산, 알러지 경고야. 개발자가 보고 바로 코딩할 수 있을 수준의 상세한 PRD를 작성해줘.',
    tags: ['설계', '기획', '문서'],
  },
  {
    id: 'wireframe',
    word: 'Wireframe (와이어프레임)',
    category: Category.PLANNING,
    definition: '디자인 들어가기 전, 화면의 구조와 배치를 선(Wire)과 상자로 단순하게 그린 설계도입니다.',
    simpleExplanation: '본격적으로 색칠하기 전에 연필로 대충 그리는 "밑그림"입니다. 버튼은 여기, 그림은 저기에 둘지 위치를 잡는 단계입니다.',
    analogy: '만화를 그리기 전에 졸라맨으로 대충 구도를 잡는 콘티(Story board)와 같습니다.',
    examplePrompt: '반려동물 앱의 메인 화면 와이어프레임을 그리려고 해. 상단에는 어떤 정보가 와야 하고, 하단 네비게이션에는 어떤 버튼들이 필요한지 텍스트로 구조를 짜줘.',
    tags: ['설계', '디자인', '밑그림'],
  },
  {
    id: 'user-flow',
    word: 'User Flow (유저 플로우)',
    category: Category.PLANNING,
    definition: '사용자가 서비스를 이용하면서 이동하는 경로와 흐름을 시각화한 것입니다.',
    simpleExplanation: '쇼핑몰에 들어와서 물건을 사고 결제하고 나갈 때까지 사용자가 밟는 "동선" 지도입니다.',
    analogy: '보물찾기 지도와 같아요. 입구에서 출발해서 어떤 길을 따라가야 보물(결제 완료)에 도착하는지 그려놓은 것입니다.',
    examplePrompt: '사용자가 앱을 켜서 회원가입을 하고, 첫 번째 식단을 기록하는 과정까지의 User Flow를 단계별로 정리해줘.',
    tags: ['기획', '동선', '흐름'],
  },
  {
    id: 'agile',
    word: 'Agile (애자일)',
    category: Category.PLANNING,
    definition: '소프트웨어 개발 방식 중 하나로, 완벽한 계획보다는 빠르고 유연하게 대응하며 점진적으로 개발하는 방법론입니다.',
    simpleExplanation: '처음부터 완벽하게 만들려고 몇 달을 고민하는 대신, 일단 만들어서 보여주고 고치고를 반복하며 빠르게 완성해가는 방식입니다.',
    analogy: '여행 계획을 1분 단위로 짜고 출발하는 패키지 여행(폭포수 모델)이 아니라, 나침반만 들고 일단 떠나서 상황에 맞춰 경로를 바꾸는 배낭 여행입니다.',
    examplePrompt: '우리 팀은 애자일 방식으로 앱을 개발하려고 해. 2주 단위로 스프린트를 진행할 건데, 첫 번째 MVP(최소 기능 제품) 배포를 위한 핵심 기능 우선순위를 정해줘.',
    tags: ['방법론', '협업', '유연성'],
  },
  {
    id: 'scrum',
    word: 'Scrum (스크럼)',
    category: Category.PLANNING,
    definition: '애자일 방법론을 실천하기 위한 구체적인 규칙과 절차(프레임워크)입니다. 팀이 하나가 되어 짧은 주기로 목표를 달성합니다.',
    simpleExplanation: '애자일이 "철학"이라면 스크럼은 "실천 규칙"입니다. 매일 아침 짧게 회의하고(데일리 스크럼), 주기적으로 되돌아보는 시간을 갖습니다.',
    analogy: '럭비 경기에서 선수들이 어깨를 걸고 뭉쳐 전진하는 대형(Scrum)에서 따왔습니다. 팀원들이 똘똘 뭉쳐서 단기간에 골(목표)을 넣는 전술입니다.',
    examplePrompt: '개발 팀의 스크럼 마스터 역할을 맡아줘. 오늘 진행할 데일리 스크럼 회의에서 팀원들에게 물어봐야 할 3가지 핵심 질문을 작성해줘.',
    tags: ['방법론', '팀워크', '프로세스'],
  },
  {
    id: 'refactoring',
    word: 'Refactoring (리팩토링)',
    category: Category.CODING,
    definition: '코드의 기능은 바꾸지 않으면서, 내부 구조를 더 이해하기 쉽고 수정하기 쉽게 정리하는 작업입니다.',
    simpleExplanation: '글의 내용은 그대로 두고, 맞춤법을 고치고 문단을 나누어 읽기 좋게 다듬는 "퇴고" 과정입니다.',
    analogy: '방청소와 같아요. 방에 있는 물건(기능)은 그대로지만, 옷은 옷장에, 책은 책꽂이에 정리해서 나중에 찾기 쉽게 만드는 것입니다.',
    examplePrompt: '작성해준 파이썬 코드가 너무 길고 복잡해. 기능은 똑같이 유지하되, 초보자도 읽기 쉽도록 변수명을 직관적으로 바꾸고 함수를 분리해서 리팩토링해줘.',
    tags: ['정리', '코드품질', '청소'],
  },
  {
    id: 'hard-coding',
    word: 'Hard Coding (하드코딩)',
    category: Category.CODING,
    definition: '데이터를 코드 내부에 직접 고정된 값으로 박아넣는 방식입니다. 유연하지 못하여 수정이 어렵습니다.',
    simpleExplanation: '계산기 앱을 만드는데 "1+1"만 되게 만들고, "2+3"을 하려면 앱을 다시 만들어야 하는 것과 비슷합니다.',
    analogy: '안내판에 글씨를 매직으로 써놓은 것과 같아요. 내용을 바꾸려면 안내판을 부수고 다시 만들어야 하죠. (반대는 칠판에 분필로 쓰는 것)',
    examplePrompt: '이 코드에서 API 키나 색상 값처럼 나중에 바뀔 수 있는 정보는 하드코딩하지 말고, 별도의 설정 파일이나 변수로 빼서 관리하기 쉽게 수정해줘.',
    tags: ['코딩', '실수', '고정'],
  },
  {
    id: 'comment',
    word: 'Comment (주석)',
    category: Category.CODING,
    definition: '코드를 실행할 때는 무시되지만, 개발자가 코드를 이해하기 위해 적어놓는 메모입니다.',
    simpleExplanation: '코드 옆에 달아두는 "포스트잇 메모"입니다. 컴퓨터는 안 읽고 사람만 읽습니다.',
    analogy: '요리책 귀퉁이에 "이 부분에서는 불을 약하게 줄이세요"라고 연필로 적어둔 팁과 같습니다.',
    examplePrompt: '이 코드가 무슨 역할을 하는지 초보자인 내가 이해할 수 있게, 중요한 로직마다 한글로 친절하게 주석(Comment)을 달아줘.',
    tags: ['설명', '메모', '가이드'],
  },
  {
    id: 'database',
    word: 'Database (DB)',
    category: Category.DATA_ANALYSIS,
    definition: '데이터를 체계적으로 저장하고 관리하는 시스템입니다.',
    simpleExplanation: '엑셀 파일들을 엄청나게 많이, 그리고 안전하게 모아둔 "디지털 서류 창고"입니다.',
    analogy: '도서관의 서고와 같아요. 책(데이터)이 마구잡이로 쌓여있지 않고, 번호표(인덱스)에 따라 정리되어 있어서 사서(DBMS)가 금방 찾을 수 있죠.',
    examplePrompt: '사용자 정보를 저장할 데이터베이스 스키마를 짜줘. 이름, 이메일, 가입일, 최근 접속일 필드가 필요해.',
    tags: ['데이터', '저장소', '창고'],
  },
  {
    id: 'sql',
    word: 'SQL',
    category: Category.DATA_ANALYSIS,
    definition: 'Structured Query Language. 데이터베이스에서 데이터를 가져오거나 수정하기 위해 사용하는 표준 언어입니다.',
    simpleExplanation: '데이터 창고지기(DB)에게 "이것 좀 찾아줘"라고 시킬 때 쓰는 "주문서 양식"입니다.',
    analogy: '외국인 직원에게 일을 시킬 때 그 나라 말로 해야 하듯, DB랑 대화하려면 SQL이라는 언어로 말해야 알아듣습니다.',
    examplePrompt: 'Orders 테이블에서 지난달 매출이 100만원 이상인 고객 명단을 뽑는 SQL 쿼리문을 작성해줘.',
    tags: ['데이터', '언어', '질의'],
  },
  {
    id: 'dashboard',
    word: 'Dashboard (대시보드)',
    category: Category.DATA_ANALYSIS,
    definition: '데이터를 시각화하여 현재 상태나 성과를 한눈에 파악할 수 있게 만든 화면입니다.',
    simpleExplanation: '자동차 계기판처럼, 우리 서비스가 잘 돌아가고 있는지 그래프와 숫자로 보여주는 "상황판"입니다.',
    analogy: '자동차 운전석 앞의 계기판입니다. 속도, 기름양, 엔진 온도를 한눈에 보고 운전하듯, 회사 운영 상황을 한눈에 보는 것이죠.',
    examplePrompt: '관리자 페이지에 들어갈 대시보드를 기획해줘. 일일 방문자 수, 매출액, 회원가입 추이를 보여주는 그래프 배치를 제안해줘.',
    tags: ['시각화', '그래프', '통계'],
  },
  {
    id: 'eda',
    word: 'EDA (탐색적 데이터 분석)',
    category: Category.DATA_ANALYSIS,
    definition: 'Exploratory Data Analysis. 본격적인 분석 전에 데이터를 그래프로 그려보거나 통계량을 내보며 데이터의 특징을 훑어보는 과정입니다.',
    simpleExplanation: '데이터의 "첫인상"을 확인하는 단계입니다. 이상한 값은 없는지, 어떤 경향이 있는지 가볍게 탐색하는 것입니다.',
    analogy: '소개팅 나가기 전에 상대방 SNS를 쭉 훑어보면서 "아 이런 음식을 좋아하는구나", "여행을 자주 가는구나" 하고 대략적인 성향을 파악하는 것과 같습니다.',
    examplePrompt: '고객 구매 내역 데이터(CSV)가 있어. 이 데이터로 본격적인 예측 모델을 만들기 전에, 파이썬 Pandas와 Seaborn을 사용해 EDA를 수행하는 코드를 짜줘. 결측치 확인과 가격 분포 시각화를 포함해줘.',
    tags: ['분석', '탐색', '시각화'],
  },
  {
    id: 'regression',
    word: 'Regression Analysis (회귀 분석)',
    category: Category.DATA_ANALYSIS,
    definition: '변수들 사이의 관계를 모델링하여, 하나의 변수가 변할 때 다른 변수가 어떻게 변하는지 예측하는 분석 방법입니다.',
    simpleExplanation: '원인과 결과의 관계를 수학 공식으로 만드는 것입니다. "기온이 1도 오르면 아이스크림이 몇 개 더 팔릴까?"를 예측합니다.',
    analogy: '부모님의 키(원인)를 알면 자녀의 예상 키(결과)를 대략 맞출 수 있는 공식을 만드는 것과 비슷합니다.',
    examplePrompt: '광고비 지출액에 따른 매출액 변화 데이터를 가지고 있어. 선형 회귀 분석(Linear Regression)을 통해 광고비를 100만 원 늘리면 매출이 얼마나 오를지 예측하는 모델을 파이썬으로 만들어줘.',
    tags: ['예측', '통계', '원인결과'],
  },
  {
    id: 'time-series',
    word: 'Time Series Analysis (시계열 분석)',
    category: Category.DATA_ANALYSIS,
    definition: '시간의 흐름에 따라 기록된 데이터를 분석하여 과거의 패턴을 파악하고 미래를 예측하는 기법입니다.',
    simpleExplanation: '시간 순서대로 된 데이터(주식, 날씨, 매출)를 보고 "내일은 어떨까?"를 맞추는 것입니다.',
    analogy: '지난 10년 동안의 크리스마스 날씨 기록을 보고, "올해 크리스마스에도 눈이 올 확률이 높겠다"라고 예상하는 것입니다.',
    examplePrompt: '지난 3년 간의 월별 웹사이트 방문자 수 데이터가 있어. 이 데이터의 계절적 패턴(Seasonality)을 분석하고, 다음 달 방문자 수를 예측하는 시계열 분석 코드를 작성해줘.',
    tags: ['예측', '시간', '트렌드'],
  },
  {
    id: 'funnel',
    word: 'Funnel Analysis (퍼널 분석)',
    category: Category.DATA_ANALYSIS,
    definition: '사용자가 서비스에 진입해서 최종 목표(예: 결제)까지 도달하는 과정을 단계별로 분석하여 이탈 지점을 찾는 기법입니다.',
    simpleExplanation: '깔때기(Funnel)처럼 입구는 넓지만 출구는 좁습니다. 어디서 사람들이 줄줄 새어나가는지(이탈) 범인을 찾는 수사 기법입니다.',
    analogy: '쇼핑몰에 100명이 들어왔는데 결제는 5명만 했다면, 나머지 95명이 "장바구니"에서 나갔는지 "로그인"에서 나갔는지 확인해서 구멍을 메우는 작업입니다.',
    examplePrompt: '쇼핑몰 앱의 구매 전환율을 높이고 싶어. [메인 홈 -> 상세 페이지 -> 장바구니 -> 결제 페이지 -> 결제 완료] 단계별로 퍼널 분석을 하려고 하는데, 어떤 지표를 중점적으로 봐야 할지 알려줘.',
    tags: ['마케팅', '성장', '깔때기'],
  },
  {
    id: 'cluster',
    word: 'Cluster Analysis (군집 분석)',
    category: Category.DATA_ANALYSIS,
    definition: '데이터를 특성이 비슷한 것끼리 여러 그룹(Cluster)으로 묶는 분석 방법입니다.',
    simpleExplanation: '섞여 있는 구슬들을 색깔이나 크기가 비슷한 것끼리 나누어 담는 분류 작업입니다.',
    analogy: '도서관에 쌓여있는 책들을 내용에 따라 "소설", "과학", "역사" 코너로 분류하거나, 빨래를 "흰 옷", "색깔 옷", "수건"으로 나누는 것과 같습니다.',
    examplePrompt: '고객들의 구매 패턴(구매 금액, 방문 횟수)을 바탕으로 고객 등급을 나누고 싶어. K-Means 알고리즘을 사용해서 고객을 3개의 그룹으로 군집화(Clustering)하는 파이썬 예제 코드를 보여줘.',
    tags: ['분류', '그룹', '패턴'],
  },
  {
    id: 'ab-test',
    word: 'A/B Test (A/B 테스트)',
    category: Category.DATA_ANALYSIS,
    definition: '두 가지 버전(A안, B안)을 만들어 사용자 반응을 비교분석하는 실험 방법입니다.',
    simpleExplanation: '짜장면이 잘 팔릴지 짬뽕이 잘 팔릴지 모르겠을 때, 반반 메뉴를 내놓고 손님들이 뭘 더 많이 먹나 지켜보는 것입니다.',
    analogy: '안과에서 시력 검사할 때 "이게 잘 보이세요, 저게 잘 보이세요?" 하고 렌즈를 바꿔가며 최적의 도수를 찾는 과정과 같습니다.',
    examplePrompt: '회원가입 버튼 색깔을 파란색(A)과 빨간색(B) 중 어떤 걸로 할지 고민이야. A/B 테스트를 하는 절차와 측정해야 할 지표를 알려줘.',
    tags: ['실험', '비교', '최적화'],
  },
  {
    id: 'kpi',
    word: 'KPI (핵심 성과 지표)',
    category: Category.DATA_ANALYSIS,
    definition: 'Key Performance Indicator. 목표를 성공적으로 달성하고 있는지 측정하는 가장 중요한 숫자(지표)입니다.',
    simpleExplanation: '성적표의 "전교 등수"나 다이어트의 "체지방률"처럼, 내가 잘하고 있는지 판단하는 기준 점수입니다.',
    analogy: '자동차 계기판에 많은 숫자가 있지만, 과속하지 않고 목적지에 가기 위해 가장 중요한 건 "속도계(KPI)"입니다.',
    examplePrompt: '새로 런칭한 SNS 서비스의 성공 여부를 판단하기 위한 핵심 KPI를 3가지만 추천해줘. 단순 방문자 수보다는 사용자의 활동성(Engagement)을 측정하고 싶어.',
    tags: ['지표', '성적표', '목표'],
  },
  {
    id: 'cr',
    word: 'Conversion Rate (전환율)',
    category: Category.DATA_ANALYSIS,
    definition: '웹사이트 방문자 중 회원가입, 구매 등 목표한 행동(Conversion)을 실제로 수행한 사람의 비율입니다.',
    simpleExplanation: '구경만 하던 손님이 진짜 물건을 사는 손님으로 "변신"한 비율입니다.',
    analogy: '옷가게에 100명이 들어왔는데 3명만 옷을 사서 나갔다면, 이 가게의 구매 전환율(CR)은 3%입니다.',
    examplePrompt: '우리 웹사이트의 방문자는 많은데 회원가입 전환율(CR)이 1%로 너무 낮아. 전환율을 높이기 위해 랜딩 페이지에서 개선해야 할 UX 요소들을 제안해줘.',
    tags: ['마케팅', '비율', '성과'],
  },
  {
    id: 'churn',
    word: 'Churn Rate (이탈률)',
    category: Category.DATA_ANALYSIS,
    definition: '일정 기간 동안 서비스를 이용하다가 더 이상 이용하지 않게 된(구독 취소, 탈퇴) 고객의 비율입니다.',
    simpleExplanation: '단골 손님이 발길을 끊는 비율입니다. 이 숫자가 높으면 구멍 난 독에 물 붓기입니다.',
    analogy: '양동이에 물(고객)을 계속 채워도 바닥에 구멍(이탈)이 나 있으면 물이 차오르지 않죠. 그 구멍의 크기를 나타냅니다.',
    examplePrompt: '구독형 서비스의 이탈률(Churn Rate)을 줄이고 싶어. 이탈하려는 사용자를 잡기 위한 "해지 방어" 전략이나 프로모션 아이디어를 5가지 제안해줘.',
    tags: ['유지', '방어', '감소'],
  },
  {
    id: 'significance',
    word: 'Statistical Significance (통계적 유의성)',
    category: Category.DATA_ANALYSIS,
    definition: '분석 결과가 단순한 우연이라기보다, 실제로 의미가 있다고 확신할 수 있는 정도입니다.',
    simpleExplanation: '"에이, 그거 그냥 우연히 운 좋아서 그런 거 아니야?"라는 의심을 잠재울 수 있는 확실한 증거입니다.',
    analogy: '동전을 3번 던져서 다 앞면이 나오면 "운이 좋네" 하지만, 100번 던져서 다 앞면이 나오면 "이 동전은 조작됐어(유의하다)"라고 확신하는 것과 같습니다.',
    examplePrompt: 'A/B 테스트 결과 B안의 클릭률이 2% 더 높게 나왔어. 이 차이가 통계적으로 유의미한지(Statistical Significance) 확인하려면 어떤 검정 방법을 써야 해?',
    tags: ['통계', '확신', '검증'],
  },
  {
    id: 'p-value',
    word: 'P-value (유의확률)',
    category: Category.DATA_ANALYSIS,
    definition: '내 가설이 틀렸을 확률(우연일 확률)을 나타내는 지표입니다. 보통 0.05(5%)보다 작으면 "통계적으로 유의하다"고 봅니다.',
    simpleExplanation: '이 결과가 "운빨(우연)"일 확률입니다. 이 숫자가 아주 작아야 "운이 아니라 실력(진짜 효과)"이라고 인정받습니다.',
    analogy: '로또 1등 당첨될 확률처럼 P-value가 0에 가까울수록, "와, 이건 우연히 일어날 수 없는 일이야!"라고 인정하게 됩니다.',
    examplePrompt: '데이터 분석 결과 P-value가 0.03이 나왔어. 일반적인 기준(0.05)에서 이 결과를 어떻게 해석해야 하는지, 비전공자 팀장님께 보고할 멘트를 작성해줘.',
    tags: ['통계', '확률', '기준'],
  },
  {
    id: 'ltv',
    word: 'LTV (고객 생애 가치)',
    category: Category.DATA_ANALYSIS,
    definition: 'Lifetime Value. 한 명의 고객이 서비스에 가입해서 이탈할 때까지 평생 동안 지불할 것으로 예상되는 총금액입니다.',
    simpleExplanation: '이 손님이 평생 우리 가게에 얼마를 써줄까? 를 돈으로 계산한 것입니다.',
    analogy: '단골 손님 한 명을 얻으면, 그 사람이 오늘 밥값 1만 원만 내는 게 아니라 앞으로 10년 동안 1,000만 원을 써줄 귀한 손님(LTV가 높은 고객)으로 보는 것입니다.',
    examplePrompt: '고객 한 명을 데려오는 데 쓰는 돈(CAC)이 5만 원인데, LTV는 얼마가 되어야 이 사업이 안정적일까? LTV와 CAC의 이상적인 비율과 계산 방법을 알려줘.',
    tags: ['가치', '수익', '장기'],
  },
  {
    id: 'log',
    word: 'Log (로그)',
    category: Category.DATA_ANALYSIS,
    definition: '시스템의 작동 내역, 사용자 활동, 에러 발생 시점 등을 시간 순서대로 기록한 데이터입니다.',
    simpleExplanation: '비행기의 "블랙박스"나 선장의 "항해일지"처럼, 앱 안에서 일어난 모든 일을 꼬박꼬박 적어둔 일기입니다.',
    analogy: '편의점 CCTV 녹화본입니다. 누가 언제 들어와서 뭘 훔쳐갔는지(에러 발생) 나중에 돌려보며 범인을 잡을 수 있죠.',
    examplePrompt: '사용자가 장바구니에 물건을 담을 때마다, 어떤 물건을 언제 담았는지 서버에 로그를 남기도록 코드를 짜줘.',
    tags: ['기록', '추적', '역사'],
  },
  {
    id: 'markdown',
    word: 'Markdown (마크다운)',
    category: Category.PROMPTING,
    definition: '텍스트 기반의 가벼운 마크업 언어로, 특수기호(#, *, -)를 사용해 글자 크기나 목록 등을 간단하게 꾸미는 규칙입니다.',
    simpleExplanation: 'AI랑 대화할 때 글씨를 굵게 하거나, 제목을 달거나, 표를 그리기 위해 사용하는 "글꾸미기 약속"입니다.',
    analogy: '카카오톡에서 샵(#)을 붙이면 검색이 되는 것처럼, 글 앞에 #을 붙이면 제목이 되고, -를 붙이면 리스트가 되는 간단한 규칙입니다.',
    examplePrompt: '이 내용을 읽기 좋게 정리해줘. 중요한 단어는 **볼드체**로 강조하고, 단계별 설명은 마크다운 번호 리스트(1., 2.)로 작성해줘.',
    tags: ['문서', '형식', '글쓰기'],
  },
  {
    id: 'meta-prompt',
    word: 'Meta Prompt (메타 프롬프트)',
    category: Category.PROMPTING,
    definition: '프롬프트(지시어)를 생성하거나 개선하기 위해 사용하는 프롬프트입니다.',
    simpleExplanation: 'AI에게 "내가 일을 더 잘 시킬 수 있게, 주문하는 방법을 알려줘"라고 주문하는 것입니다.',
    analogy: '소원을 들어주는 지니에게 "소원을 비는 가장 완벽한 문장을 알려줘"라고 첫 번째 소원을 비는 것과 같습니다.',
    examplePrompt: '나는 "여행 계획 짜주는 봇"을 만들고 싶어. AI가 최고의 답변을 내놓도록 하려면 내가 처음에 어떤 프롬프트(지시문)를 입력해야 할까? 그 프롬프트를 작성해줘.',
    tags: ['주문법', '최적화', '고급'],
  },
  {
    id: 'api',
    word: 'API',
    category: Category.CODING,
    definition: 'Application Programming Interface. 서로 다른 소프트웨어끼리 정보를 주고받기 위한 약속이나 통로입니다.',
    simpleExplanation: '내 앱이 다른 서비스(예: 구글 지도, 날씨 정보)의 기능을 빌려다 쓸 수 있게 해주는 "연결 고리"입니다.',
    analogy: '식당의 "점원"입니다. 손님(내 앱)이 주방(다른 서비스)에 직접 들어가지 않고, 점원(API)에게 메뉴를 시키면 음식을 가져다 주는 것과 같습니다.',
    examplePrompt: '내 웹사이트에 현재 날씨를 보여주고 싶어. 무료로 사용할 수 있는 날씨 API를 추천해주고, 자바스크립트로 그 API를 연결하는 예시 코드를 짜줘.',
    tags: ['연결', '데이터', '통신'],
  },
  {
    id: 'frontend-backend',
    word: 'Frontend / Backend',
    category: Category.CODING,
    definition: '웹사이트에서 사용자가 보는 화면(Frontend)과 보이지 않는 곳에서 데이터를 처리하는 영역(Backend)입니다.',
    simpleExplanation: '프론트엔드는 "화면과 디자인", 백엔드는 "데이터와 서버"입니다.',
    analogy: '식당으로 치면 프론트엔드는 "홀(식탁, 메뉴판, 인테리어)"이고, 백엔드는 "주방(요리, 재료 손질, 설거지)"입니다.',
    examplePrompt: '간단한 메모장 앱을 만들 건데, 프론트엔드는 React로 하고 백엔드는 없이 브라우저 저장소(Local Storage)만 사용해서 구현해줘.',
    tags: ['구조', '개발분야'],
  },
  {
    id: 'debugging',
    word: 'Debugging (디버깅)',
    category: Category.CODING,
    definition: '소프트웨어의 버그(오류)를 찾아내고 수정하는 과정입니다.',
    simpleExplanation: '앱이 예상대로 작동하지 않을 때, 원인을 찾아서 고치는 "수리" 작업입니다.',
    analogy: '의사 선생님이 환자의 증상을 듣고(에러 로그), 어디가 아픈지 진찰해서(원인 파악), 약을 처방하는(코드 수정) 과정입니다.',
    examplePrompt: '이 코드를 실행했더니 "NullReferenceException"이라는 에러가 떴어. 이 에러가 무슨 뜻이고, 코드의 어느 부분이 잘못되었는지 찾아서 고쳐줘.',
    tags: ['수리', '에러', '고치기'],
  },
  {
    id: 'ui-ux',
    word: 'UI / UX',
    category: Category.DESIGN,
    definition: 'User Interface(사용자 인터페이스)와 User Experience(사용자 경험)입니다.',
    simpleExplanation: 'UI는 "어떻게 생겼나(디자인, 버튼 위치)"이고, UX는 "써보니 편한가(느낌, 편의성)"입니다.',
    analogy: '케첩 병으로 치면, UI는 병의 모양과 색깔이고, UX는 케첩이 푹 나오지 않고 적당히 나오도록 만든 입구의 설계입니다.',
    examplePrompt: '노인분들이 사용할 건강 앱이야. UI는 글씨가 크고 명확해야 하고, UX는 복잡한 단계 없이 버튼 하나로 해결되도록 쉽게 기획해줘.',
    tags: ['디자인', '사용자', '경험'],
  },
    {
    id: 'library-framework',
    word: 'Library / Framework',
    category: Category.CODING,
    definition: '개발을 쉽게 하기 위해 미리 만들어진 코드의 집합(라이브러리)과 뼈대(프레임워크)입니다.',
    simpleExplanation: '맨땅에 헤딩하지 않고, 남들이 만들어둔 도구를 가져다 쓰는 것입니다.',
    analogy: '라이브러리는 "공구 상자(망치, 톱)"라서 내가 필요할 때 꺼내 쓰는 것이고, 프레임워크는 "밀키트"나 "모델하우스"처럼 이미 기본 구조가 잡혀있어 그 안에서 요리하거나 꾸미는 것입니다.',
    examplePrompt: '웹사이트를 예쁘게 꾸미고 싶은데 CSS를 처음부터 짜기 힘들어. 초보자가 쓰기 좋은 CSS 프레임워크(예: Tailwind, Bootstrap)를 추천해주고 사용법을 알려줘.',
    tags: ['도구', '장비', '기반'],
  },
  {
    id: 'deploy',
    word: 'Deploy (배포)',
    category: Category.INFRA,
    definition: '개발한 소프트웨어를 실제 사용자가 사용할 수 있는 환경(서버 등)에 올리는 것입니다.',
    simpleExplanation: '내 컴퓨터에서만 되던 프로그램을, 친구들도 인터넷으로 접속할 수 있게 "인터넷에 올리는 것"입니다.',
    analogy: '집에서 혼자 쓴 소설(개발)을 출판해서 서점에 깔아두는 것(배포)과 같습니다.',
    examplePrompt: '내가 만든 HTML 파일을 친구들에게 보여주고 싶어. 돈 안 들이고 "Vercel"이나 "Netlify"를 이용해서 무료로 배포하는 방법을 순서대로 알려줘.',
    tags: ['출시', '공유', '서버'],
  }
];